In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./dataset/pandas_full_practice.csv")
df.head()

,user_id,age,gender,city,salary,experience_years,department,performance_score,joining_year
0,1,56.0,Female,Bangalore,NaN,3.0,IT,NaN,NaN
1,2,NaN,Male,Delhi,NaN,11.0,Finance,NaN,NaN
2,3,46.0,Male,NaN,55000.0,NaN,HR,5.0,2024.0
3,4,32.0,Male,Pune,NaN,1.0,Finance,NaN,2022.0
4,5,NaN,Male,Bangalore,115000.0,NaN,NaN,NaN,2024.0

In [3]:
df.columns, df.shape

(Index(['user_id', 'age', 'gender', 'city', 'salary', 'experience_years',
        'department', 'performance_score', 'joining_year'],
       dtype='str'),
 (1000, 9))

In [4]:
df.isna().sum()

user_id                0
age                  194
gender                48
city                 176
salary               451
experience_years     428
department           194
performance_score    518
joining_year         259
dtype: int64

In [5]:
df.groupby("gender")["salary"].sum().sort_values(ascending=False)

gender
Male      20845000.0
Female    20650000.0
Other      1910000.0
Name: salary, dtype: float64

In [6]:
df.groupby("gender")["salary"].sum().sort_values(ascending=False)

gender
Male      20845000.0
Female    20650000.0
Other      1910000.0
Name: salary, dtype: float64

In [7]:
df.groupby(["gender", "department"])["department"].sum().sort_values(ascending=False)

gender  department
Female  Sales         SalesSalesSalesSalesSalesSalesSalesSalesSalesS...
Male    Sales         SalesSalesSalesSalesSalesSalesSalesSalesSalesS...
Other   Sales         SalesSalesSalesSalesSalesSalesSalesSalesSalesS...
Male    IT            ITITITITITITITITITITITITITITITITITITITITITITIT...
Female  IT            ITITITITITITITITITITITITITITITITITITITITITITIT...
Other   IT                                               ITITITITITITIT
Male    HR            HRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHR...
Female  HR            HRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHRHR...
Other   HR                                               HRHRHRHRHRHRHR
Female  Finance       FinanceFinanceFinanceFinanceFinanceFinanceFina...
Male    Finance       FinanceFinanceFinanceFinanceFinanceFinanceFina...
Other   Finance       FinanceFinanceFinanceFinanceFinanceFinanceFina...
Name: department, dtype: str

In [8]:
df.groupby(["gender", "department"])["salary"].sum().sort_values(ascending=False)

gender  department
Male    Sales         5230000.0
Female  Finance       4875000.0
        Sales         4750000.0
        HR            4500000.0
Male    IT            4220000.0
        HR            3980000.0
        Finance       3885000.0
Female  IT            3570000.0
Other   Finance        675000.0
        Sales          310000.0
        HR             260000.0
        IT             140000.0
Name: salary, dtype: float64

## Payments Data

In [11]:
payments = pd.read_csv("./dataset/payments.csv")
payments.head()

     name gender  amount month       city payment_method     category
0   Aarav      M  1200.0   Jan  Ahmedabad            UPI         Food
1  Vivaan      M  1500.0   Jan     Mumbai           Card     Shopping
2  Aditya      M     NaN   Jan      Delhi           Cash        Bills
3  Vihaan      M  1100.0   Jan       Pune            UPI    Transport
4   Arjun      M  2000.0   Jan  Bangalore           Card  Electronics

In [19]:
payments.info(), payments.shape

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            99 non-null     str
 1   gender          100 non-null    str
 2   amount          83 non-null     float64
 3   month           100 non-null    str
 4   city            100 non-null    str
 5   payment_method  100 non-null    str
 6   category        100 non-null    str
dtypes: float64(1), str(6)
memory usage: 5.6 KB

(None, (100, 7))

In [35]:
df = payments.groupby(["city", "payment_method"])["amount"].sum().reset_index(name="abc")
df

         city payment_method      abc
0   Ahmedabad           Card  11410.0
1   Ahmedabad           Cash      0.0
2   Ahmedabad            UPI  12900.0
3   Bangalore           Card  22000.0
4       Delhi           Cash  10800.0
5       Delhi            UPI  12250.0
6   Hyderabad            UPI  13200.0
7      Mumbai           Card  15300.0
8      Mumbai            UPI  11350.0
9        Pune           Card  20450.0
10       Pune           Cash   9400.0
11       Pune            UPI   1100.0

In [38]:
df.pivot_table(index="city", columns="payment_method", values="abc", aggfunc="sum")

payment_method     Card     Cash      UPI
city
Ahmedabad       11410.0      0.0  12900.0
Bangalore       22000.0      NaN      NaN
Delhi               NaN  10800.0  12250.0
Hyderabad           NaN      NaN  13200.0
Mumbai          15300.0      NaN  11350.0
Pune            20450.0   9400.0   1100.0